# 🌍 AI Travel Planner Configuration
# Customize the name below to match your preference
name = "cf-ai-travel-planner"
main = "src/index.js"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Workers AI binding (enables LLaMA 3.3 access)
[ai]
binding = "AI"

# Durable Objects for user memory
[[durable_objects.bindings]]
name = "TRAVEL_MEMORY"
class_name = "TravelMemory"

# Durable Objects migration (SQLite for free plan)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["TravelMemory"]

# Workflow Engine binding for orchestration (preview feature)
# Uncomment when Workflows is available in your account
# [[workflows]]
# binding = "MY_WORKFLOW"
# class_name = "TravelWorkflow"

# NOTE: API keys are stored as secrets, not vars
# Use: wrangler secret put WEATHER_API_KEY
# Use: wrangler secret put EVENTS_API_KEY

# Optional: KV namespace for caching (uncomment and add IDs if needed)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Production environment (uncomment for custom domain)
# [env.production]
# name = "cf-ai-travel-planner-production"
# routes = [
#   { pattern = "travel.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# Staging environment (optional)
# [env.staging]
# name = "cf-ai-travel-planner-staging"